config/routes.rb
Rails.application.routes.draw do
  resources :residents
  resources :rooms
  devise_for :users
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resident.rb
class Resident < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  belongs_to :room

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :door_number, presence: true, uniqueness: true
  has_many :residents

  scope :available, lambda {
    includes(:residents).where(residents: { room_id: nil })
  }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception, prepend: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @total_residents = Resident.count
    @total_rooms = Room.count
    @available_room_count = Room.available.count
  end
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_action :set_resident, only: %i[show edit update destroy]

  def index
    @residents = Resident.all
  end

  def show; end

  def new
    @resident = Resident.new
  end

  def edit; end

  def create
    @resident = Resident.new(resident_params)

    if @resident.save
      redirect_to @resident, notice: 'Resident was successfully created.'
    else
      render :new
    end
  end

  def update
    if @resident.update(resident_params)
      redirect_to @resident, notice: 'Resident was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @resident.destroy
    redirect_to residents_url, notice: 'Resident was successfully deleted.'
  end

  private

  def set_resident
    @resident = Resident.find(params[:id])
  end

  def resident_params
    params.require(:resident).permit(:first_name, :last_name, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = Room.all
  end

  def show; end

  def new
    @room = Room.new
  end

  def edit; end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully deleted.'
  rescue ActiveRecord::InvalidForeignKey
    message = 'Room has residents attached, please remove first.'
    redirect_to rooms_url, notice: message
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:door_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canary_helper.rb
module CanaryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<h1>CareSourcery</h1>
<p>A home for retired adventurers.</p>

<table>
  <tr>
    <th>Total Rooms</th>
    <th>Total Residents</th>
    <th>Vacant Rooms</th>
  </tr>
  <tr>
    <td><%= @total_rooms %></td>
    <td><%= @total_residents %></td>
    <td><%= @available_room_count %></td>
  </tr>
</table>

<p>
  <%= link_to 'Add Room', new_room_path, class: 'button' %>
  <%= link_to 'Add Resident', new_resident_path, class: 'button' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareSourcery</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
    <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="menu">
      <%= render 'devise/menu/login_items' %>
      <% if user_signed_in? %>
      <li> <%= link_to('Home', '/')  %> </li>
      <li> <%= link_to('Rooms', rooms_path)  %> </li>
      <li> <%= link_to('Residents', residents_path)  %>  </li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/residents/_form.html.erb
<%= form_with(model: resident, local: true) do |form| %>
  <% if resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
      <% resident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :resident_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :resident_last_name %>
  </div>

  <div class="field">
  <select name="resident[room_id]">
      <% Room.all.each do |room| %>
          <option value="<%= room.id %>"><%= room.door_number %></option>
      <% end %>
    </select>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/residents/edit.html.erb
<h1>Editing Resident</h1>

<%= render 'form', resident: @resident %>

app/views/residents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Residents</h1>

<% if @residents.any? %>
  <table>
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Room Number</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @residents.each do |resident| %>
        <tr>
          <td><%= resident.first_name %></td>
          <td><%= resident.last_name %></td>
          <td><%= link_to resident.room.door_number, resident.room %></td>
          <td><%= link_to 'Show', resident %></td>
          <td><%= link_to 'Edit', edit_resident_path(resident) %></td>
          <td><%= link_to 'Delete', resident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no residents yet.</p>
<% end %>

<br>

<%= link_to 'New Resident', new_resident_path, class: 'button' %>

app/views/residents/new.html.erb
<h1>New Resident</h1>

<%= render 'form', resident: @resident %>

app/views/residents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @resident.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @resident.last_name %>
</p>

<p>
  <strong>Room Door Number:</strong>
  <%= link_to @resident.room.door_number, @resident.room %>
</p>

<%= link_to 'Edit', edit_resident_path(@resident), class: 'button' %>
<%= link_to 'Delete', @resident, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :door_number %>
    <%= form.number_field :door_number, id: :room_door_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<% if @rooms.any? %>
  <table>
    <thead>
      <tr>
        <th>Door number</th>
        <th>Occupants</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.door_number %></td>
          <td><%= room.residents.count %></td>
          <td><%= link_to 'Show', room %></td>
          <td><%= link_to 'Edit', edit_room_path(room) %></td>
          <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no rooms yet.</p>
<% end %>

<br>

<%= link_to 'New Room', new_room_path, class: 'button' %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Door number:</strong>
  <%= @room.door_number %>
</p>

<% if @room.residents.any? %>
  <p><strong>Current Residents:</strong></p>
  <ul>
    <% @room.residents.each do |resident| %>
      <li><%= link_to resident.full_name, resident %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_room_path(@room), class: 'button' %>
<%= link_to 'Delete', @room, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %>